FROM rust:1-bookworm

RUN cargo install cargo-deb

WORKDIR /build
COPY . .

RUN sed -i 's|@BINDIR@|/usr/bin|g' install/systemd/motu-mk5d.service
RUN cargo build --release
RUN cargo deb --no-build

RUN mkdir -p /out && cp target/debian/*.deb /out/
